## API del Clima

Datos de contaminacion sonora historico NuevaYorkCity https://zenodo.org/records/3966543

#### Importamos librerias necesarias para nuestro trabajo

In [1]:
import pandas as pd  # Importar la librería pandas para manipulación y análisis de datos

In [2]:
df_acustic = pd.read_csv('../0-DataSets/1-DatosScraping/annotations.csv')
df_acustic

,split,sensor_id,audio_filename,annotator_id,borough,block,latitude,longitude,year,week,...,7-X_other-unknown-human-voice_proximity,8-1_dog-barking-whining_proximity,1_engine_presence,2_machinery-impact_presence,3_non-machinery-impact_presence,4_powered-saw_presence,5_alert-signal_presence,6_music_presence,7_human-voice_presence,8_dog_presence
0,test,0,00_026884.wav,-6,1,547,40.72951,-73.99388,2019,43,...,-1,-1,-1,1,0,-1,-1,-1,-1,-1
1,test,0,00_026884.wav,-4,1,547,40.72951,-73.99388,2019,43,...,-1,-1,1,-1,-1,-1,-1,-1,-1,-1
2,test,0,00_026884.wav,-3,1,547,40.72951,-73.99388,2019,43,...,-1,-1,1,-1,-1,-1,-1,-1,-1,-1
3,test,0,00_026884.wav,-1,1,547,40.72951,-73.99388,2019,43,...,-1,-1,-1,0,0,-1,-1,-1,-1,-1
4,test,0,00_026884.wav,0,1,547,40.72951,-73.99388,2019,43,...,-1,-1,1,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62017,validate,46,46_020807.wav,5399,1,559,40.73365,-73.98879,2018,42,...,-1,-1,0,0,0,0,1,0,0,0
62018,validate,46,46_020807.wav,5424,1,559,40.73365,-73.98879,2018,42,...,-1,-1,0,0,0,0,1,0,1,0
62019,validate,46,46_020853.wav,5337,1,559,40.73365,-73.98879,2018,34,...,far,-1,0,0,0,0,0,0,1,0
62020,validate,46,46_020853.wav,5365,1,559,40.73365,-73.98879,2018,34,...,-1,-1,0,0,0,0,0,0,0,0
62021,validate,46,46_020853.wav,5373,1,559,40.73365,-73.98879,2018,34,...,-1,-1,1,0,1,0,0,0,1,0

In [3]:
# filtrando solo las columnas a utilizar
df_acustic2 = df_acustic[['borough','latitude','longitude','year','week','day','hour','1_engine_presence']]
df_acustic3 = df_acustic2[df_acustic2['1_engine_presence'] == 1]
df_acustic3

       borough  latitude  longitude  year  week  day  hour  1_engine_presence
1            1  40.72951  -73.99388  2019    43    4     8                  1
2            1  40.72951  -73.99388  2019    43    4     8                  1
4            1  40.72951  -73.99388  2019    43    4     8                  1
5            1  40.72951  -73.99388  2019    43    4     8                  1
6            1  40.72951  -73.99388  2019    43    4     8                  1
...        ...       ...        ...   ...   ...  ...   ...                ...
62012        1  40.73365  -73.98879  2018    38    3    22                  1
62013        1  40.73365  -73.98879  2018    41    0    10                  1
62014        1  40.73365  -73.98879  2018    41    0    10                  1
62015        1  40.73365  -73.98879  2018    41    0    10                  1
62021        1  40.73365  -73.98879  2018    34    2     9                  1

[18184 rows x 8 columns]

In [4]:
df_acustic3.loc[df_acustic3['year'] == 2019, 'year'] = 2023
df_acustic3.loc[df_acustic3['year'] == 2016, 'year'] = 2024
df_acustic3.loc[df_acustic3['year'] == 2018, 'year'] = 2022
df_acustic3.loc[df_acustic3['year'] == 2017, 'year'] = 2021
df_acustic3

       borough  latitude  longitude  year  week  day  hour  1_engine_presence
1            1  40.72951  -73.99388  2023    43    4     8                  1
2            1  40.72951  -73.99388  2023    43    4     8                  1
4            1  40.72951  -73.99388  2023    43    4     8                  1
5            1  40.72951  -73.99388  2023    43    4     8                  1
6            1  40.72951  -73.99388  2023    43    4     8                  1
...        ...       ...        ...   ...   ...  ...   ...                ...
62012        1  40.73365  -73.98879  2022    38    3    22                  1
62013        1  40.73365  -73.98879  2022    41    0    10                  1
62014        1  40.73365  -73.98879  2022    41    0    10                  1
62015        1  40.73365  -73.98879  2022    41    0    10                  1
62021        1  40.73365  -73.98879  2022    34    2     9                  1

[18184 rows x 8 columns]

In [5]:
df_acustic_db = df_acustic3[df_acustic3['year'] >= 2023]
df_acustic_db

       borough  latitude  longitude  year  week  day  hour  1_engine_presence
1            1  40.72951  -73.99388  2023    43    4     8                  1
2            1  40.72951  -73.99388  2023    43    4     8                  1
4            1  40.72951  -73.99388  2023    43    4     8                  1
5            1  40.72951  -73.99388  2023    43    4     8                  1
6            1  40.72951  -73.99388  2023    43    4     8                  1
...        ...       ...        ...   ...   ...  ...   ...                ...
61941        1  40.73365  -73.98879  2023     7    4    20                  1
61958        1  40.73365  -73.98879  2023     3    4    16                  1
61989        1  40.73365  -73.98879  2023     6    6     8                  1
61990        1  40.73365  -73.98879  2023     6    6     8                  1
61991        1  40.73365  -73.98879  2023     6    6     8                  1

[3158 rows x 8 columns]

In [6]:
df_acustic3.columns

Index(['borough', 'latitude', 'longitude', 'year', 'week', 'day', 'hour',
       '1_engine_presence'],
      dtype='object')

In [9]:
df_acustic_db.to_parquet("../0-DataSets/3-DatosScrapingConETL/contaminacion_acustica_db_2023_2024.parquet")